
CREATE TABLE maxmind.api_call
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt int_positive,
  created_at tracking_at,
  created_at_date date NOT NULL GENERATED ALWAYS AS (date(created_at AT TIME ZONE 'Europe/Berlin')) STORED, -- for easy filtering by date
  duration_ms bigint NOT NULL CHECK (duration_ms >= 0),
  endpoint text NOT NULL CHECK (endpoint != ''),
  method system.http_method NOT NULL,
  page int_positive,
  result text NOT NULL,
  status_code int_gte0
);
COMMENT ON TABLE maxmind.api_call IS 'shortname: mm_call';


CREATE TABLE maxmind.geo_db_meta
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  geo_db text_medium_mandatory UNIQUE, -- natural key
  last_write_at timestamptz NOT NULL -- the last time this geo_db was written to the db. Used to determine if a new version of the geo_db is available from the API
);
COMMENT ON TABLE maxmind.geo_db_meta IS 'shortname: mm_db_m';


CREATE UNLOGGED TABLE maxmind.geoip2_network (
  geoname_id int NOT NULL,
  network cidr NOT NULL -- surrogate PK
);
CREATE INDEX ON maxmind.geoip2_network USING gist (network inet_ops);
GRANT TRUNCATE ON maxmind.geoip2_network TO lysref_cli;


CREATE UNLOGGED TABLE maxmind.geoip2_location_en (
  city_name text_medium_mandatory,
  country_iso_code varchar(2) NOT NULL CHECK (LENGTH(country_iso_code) = 2),
  country_name text_medium_mandatory,
  geoname_id int NOT NULL UNIQUE -- surrogate pk
);
GRANT TRUNCATE ON maxmind.geoip2_location_en TO lysref_cli;
