
-- internal-only
CREATE TABLE supplier.company
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  name text_medium_mandatory UNIQUE, -- natural key
  updated_at tracking_at
);
COMMENT ON TABLE supplier.company IS 'shortname: s_c';

GRANT SELECT ON supplier.company TO lysref_supplier; -- unlike employee and product, external access to company only needed due to joins in views

ALTER TABLE supplier.company ENABLE ROW LEVEL SECURITY; -- needed due to external access above

-- allow internal roles to bypass RLS
CREATE POLICY lysref_owner_all ON supplier.company TO lysref_owner USING (true) WITH CHECK (true);
CREATE POLICY lysref_server_all ON supplier.company TO lysref_server USING (true) WITH CHECK (true);

-- enforce RLS for external supplier role: only their own records should be visible
CREATE POLICY lysref_supplier_self_only ON supplier.company TO lysref_supplier USING (id = current_setting('app.company_id')::bigint);

------------------------------------------------------------------------------------------

-- edited internally, but own records visible to external supplier
CREATE TABLE supplier.employee
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_fk bigint NOT NULL REFERENCES supplier.company(id),
  created_at tracking_at,
  email text_medium_mandatory UNIQUE, -- natural key
  given_name text_medium_mandatory,
  family_name text_medium_mandatory,
  name text NOT NULL GENERATED ALWAYS AS (given_name || ' ' || family_name) STORED,
  updated_at tracking_at
);
COMMENT ON TABLE supplier.employee IS 'shortname: s_e';

GRANT SELECT ON supplier.employee TO lysref_supplier;

ALTER TABLE supplier.employee ENABLE ROW LEVEL SECURITY;
CREATE POLICY lysref_owner_all ON supplier.employee TO lysref_owner USING (true) WITH CHECK (true);
CREATE POLICY lysref_server_all ON supplier.employee TO lysref_server USING (true) WITH CHECK (true);
CREATE POLICY lysref_supplier_self_only ON supplier.employee TO lysref_supplier USING (company_fk = current_setting('app.company_id')::bigint);

------------------------------------------------------------------------------------------

-- edited internally. Fully visible to external supplier
CREATE TABLE supplier.product_category
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  description text_medium_mandatory UNIQUE,
  name text_short_mandatory UNIQUE, -- natural key
  updated_at tracking_at
);
COMMENT ON TABLE supplier.product_category IS 'shortname: s_pc';

GRANT SELECT ON supplier.product_category TO lysref_supplier;

------------------------------------------------------------------------------------------

-- edited by external supplier for his own products
CREATE TABLE supplier.product
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_fk bigint NOT NULL REFERENCES supplier.product_category (id),
  company_fk bigint NOT NULL REFERENCES supplier.company (id),
  created_at tracking_at,
  created_by tracking_created_by,
  last_user_update_by tracking_last_user_update_by,
  name text_medium_mandatory,
  units_on_order int_gte0,
  updated_at tracking_at,
  UNIQUE (company_fk, name) -- natural key
);
COMMENT ON TABLE supplier.product IS 'shortname: s_p';

GRANT ALL ON supplier.product TO lysref_supplier;

ALTER TABLE supplier.product ENABLE ROW LEVEL SECURITY;
CREATE POLICY lysref_owner_all ON supplier.product TO lysref_owner USING (true) WITH CHECK (true);
CREATE POLICY lysref_server_all ON supplier.product TO lysref_server USING (true) WITH CHECK (true);
CREATE POLICY lysref_supplier_self_only ON supplier.product TO lysref_supplier USING (company_fk = current_setting('app.company_id')::bigint);
