
CREATE TABLE lysinc.department
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  name text_short_mandatory UNIQUE,
  updated_at tracking_at
);
COMMENT ON TABLE lysinc.department IS 'shortname: l_d';


CREATE TABLE lysinc.employee
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  department_fk bigint NOT NULL REFERENCES lysinc.department(id),
  date_of_birth date NOT NULL,
  email text_short_mandatory UNIQUE,
  family_name text_short_mandatory,
  full_name text GENERATED ALWAYS AS (given_name || ' ' || family_name) STORED,
  given_name text_short_mandatory,
  honorific text_short_mandatory,
  job_title text_medium_mandatory,
  join_date date NOT NULL,
  profile_pic text_medium_mandatory,
  reports_to bigint NOT NULL REFERENCES lysinc.employee(id),
  sex lysinc.sex NOT NULL,
  updated_at tracking_at
);
COMMENT ON TABLE lysinc.employee IS 'shortname: l_e';


