
CREATE TABLE lysinc.employee
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  department text_short_mandatory,
  email text_short_mandatory UNIQUE,
  family_name text_short_mandatory,
  full_name text GENERATED ALWAYS AS (given_name || ' ' || family_name) STORED,
  given_name text_short_mandatory,
  honorific text_short_mandatory,
  job_title text_medium_mandatory,
  profile_pic text_medium_mandatory,
  reports_to bigint NOT NULL REFERENCES lysinc.employee(id),
  updated_at tracking_at
);
COMMENT ON TABLE lysinc.employee IS 'shortname: l_e';
