syntax = "proto3";

option go_package = "github.com/loveyourstack/lys-ref/cmd/refrpcsrv/pb";

package pb;

import "google/protobuf/timestamp.proto";

message DmVerticalInput {
  string name = 1;
}

/* Note: Input columns are repeated in model message below.
 * An embedded message is allowed, but in reponse, embedded message can't be flattened, so repetition is preferred.
 *
 * Note2: In response, timestamps are converted to UTC.
*/
message DmVertical {
  int64 id = 1;
  int32 campaign_count = 2;
  google.protobuf.Timestamp created_at = 3;
  google.protobuf.Timestamp updated_at = 4;
  
  string name = 5;
}