
CREATE TABLE aws.user_security_group_rule
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  security_group_rule_id text_short_mandatory UNIQUE, -- natural key. Rule ID copied from AWS console
  user_shortname text_short_mandatory -- string that must also be written in the rule's description, e.g. 'bob' or 'alice-smith'
);
COMMENT ON TABLE aws.user_security_group_rule IS 'shortname: aws_usgr';
