
CREATE TABLE publisher.author
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  created_by tracking_created_by,
  last_user_update_by tracking_last_user_update_by,
  name text_short_mandatory UNIQUE, -- natural key
  updated_at tracking_at
);
COMMENT ON TABLE publisher.author IS 'shortname: pub_a';
--- change columns with ---
CREATE TABLE publisher.author_archived 
( 
  LIKE publisher.author,
  archived_at tracking_at,
  archived_by_cascade bool NOT NULL
);
COMMENT ON TABLE publisher.author_archived IS 'shortname: pub_a_arc';

-----------------------------------------------------------------------------------------------

CREATE TABLE publisher.book
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_fk bigint NOT NULL REFERENCES publisher.author(id),
  created_at tracking_at,
  created_by tracking_created_by,
  last_user_update_by tracking_last_user_update_by,
  name text_short_mandatory NOT NULL UNIQUE,
  updated_at tracking_at,
  UNIQUE (author_fk, name) -- natural key
);
COMMENT ON TABLE publisher.book IS 'shortname: pub_b';
--- change columns with ---
CREATE TABLE publisher.book_archived 
( 
  LIKE publisher.book,
  archived_at tracking_at,
  archived_by_cascade bool NOT NULL
);
COMMENT ON TABLE publisher.book_archived IS 'shortname: pub_b_arc';
