
CREATE TABLE process.flow
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  name text_medium_mandatory UNIQUE, --natural key
  params text[] NOT NULL DEFAULT '{}',
  updated_at tracking_at
);
COMMENT ON TABLE process.flow IS 'shortname: proc_f';


CREATE TABLE process.step
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cmd text_medium_mandatory,
  created_at tracking_at,
  display_order int_positive,
  name text_medium_mandatory,
  flow_fk bigint NOT NULL REFERENCES process.flow(id) ON DELETE CASCADE, -- composition relationship
  updated_at tracking_at,
  UNIQUE (flow_fk, name) --natural key
);
COMMENT ON TABLE process.step IS 'shortname: proc_s';


CREATE TABLE process.step_link
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  depends_on_fk bigint NOT NULL REFERENCES process.step(id) ON DELETE CASCADE,
  step_fk bigint NOT NULL REFERENCES process.step(id) ON DELETE CASCADE,
  updated_at tracking_at,
  UNIQUE (step_fk, depends_on_fk) --natural key
);
COMMENT ON TABLE process.step_link IS 'shortname: proc_sl';


CREATE TABLE process.run
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  flow_fk bigint NOT NULL REFERENCES process.flow(id),
  step_id bigint NOT NULL, -- not FK: need to allow for step deletion without affecting runs
  step_name text_medium_mandatory -- step name at the moment run was created
);
COMMENT ON TABLE process.run IS 'shortname: proc_r';


CREATE TABLE process.point
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cmd text_medium_mandatory,
  created_at tracking_at,
  depends_on bigint[] NOT NULL,
  display_order int_positive,
  err_msg text NOT NULL,
  finished_at timestamptz NOT NULL,
  run_fk bigint NOT NULL REFERENCES process.run(id) ON DELETE CASCADE,
  started_at timestamptz NOT NULL,
  status process.run_status NOT NULL,
  step_id bigint NOT NULL, -- not FK: need to allow for step deletion without affecting points
  step_name text_medium_mandatory, -- step name at the moment run was created
  UNIQUE (run_fk, step_id) --natural key
);
COMMENT ON TABLE process.point IS 'shortname: proc_p';
