
CREATE TABLE system.blocked_ip
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  ip inet NOT NULL UNIQUE
);
COMMENT ON TABLE system.blocked_ip IS 'shortname: sys_bi';

GRANT SELECT,INSERT,DELETE ON system.blocked_ip TO lysref_server;


/* Note: the current login_attempt state is in the srv process, not in this table.
  This table is only used for persistence between app restarts. */
CREATE TABLE system.login_attempt
(
  created_at timestamptz NOT NULL,
  ip inet NOT NULL,
  is_blocked boolean NOT NULL,
  num_attempts int NOT NULL
);
COMMENT ON TABLE system.login_attempt IS 'shortname: sys_la';

GRANT SELECT,INSERT,DELETE,TRUNCATE ON system.login_attempt TO lysref_server;


CREATE TABLE system.srv_request
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  created_at_date date NOT NULL GENERATED ALWAYS AS (date(created_at AT TIME ZONE 'Europe/Berlin')) STORED, -- for easy filtering by date
  duration_ms bigint NOT NULL CHECK (duration_ms >= 0),
  endpoint text NOT NULL CHECK (endpoint != ''),
  ip inet NOT NULL,
  method system.http_method NOT NULL,
  status_code int_positive,
  user_name text_medium_mandatory
);
COMMENT ON TABLE system.srv_request IS 'shortname: sys_sr';

GRANT SELECT,INSERT ON system.srv_request TO lysref_server;


CREATE TABLE system.user
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  allow_multiple_sessions boolean NOT NULL DEFAULT false,
  created_at tracking_at,
  created_by tracking_created_by,
  deactivated_at timestamptz NOT NULL DEFAULT '0001-01-01 12:00:00+00',
  email text_medium_mandatory UNIQUE,
  email_verified boolean NOT NULL DEFAULT false,
  family_name text_medium_mandatory,
  force_password_change boolean NOT NULL DEFAULT false,
  given_name text_medium_mandatory,
  full_name text GENERATED ALWAYS AS (given_name || ' ' || family_name) STORED, -- doesn't need to be unique
  hashed_pw text_short_mandatory,
  is_deactivated boolean NOT NULL DEFAULT false,
  last_user_update_by tracking_last_user_update_by,
  name text_short_mandatory UNIQUE, -- natural key
  roles system.role[] NOT NULL DEFAULT '{}',
  updated_at tracking_at
);
COMMENT ON TABLE system.user IS 'shortname: sys_u';

GRANT SELECT,INSERT,UPDATE,DELETE ON system.user TO lysref_server;


/* Note: the current session state is in the srv process, not in system.session.
  system.session is only used for persistence between app restarts.

when making a DDL change to this table:
  1. stop srv process
  2. make the change, and then to system.session_history too
  3. restart srv process

system.session_history however is a normal table and its data should not be changed.
*/
CREATE TABLE system.session
(
  allow_multiple_sessions boolean NOT NULL,
  created_at timestamptz NOT NULL,
  email text NOT NULL,
  expires_at timestamptz NOT NULL,
  family_name text NOT NULL,
  force_password_change boolean NOT NULL,
  given_name text NOT NULL,
  geo_ip_country_iso_code varchar(2) NOT NULL CHECK (LENGTH(geo_ip_country_iso_code) = 2),
  geo_ip_location text_medium_mandatory,
  ip inet NOT NULL,
  last_access_at timestamptz NOT NULL,
  roles system.role[] NOT NULL,
  token text_short_mandatory,
  user_agent text_medium_mandatory,
  user_fk int NOT NULL REFERENCES system.user(id),
  user_name text_short_mandatory
);
COMMENT ON TABLE system.session IS 'shortname: sys_s';

-- change columns with --

CREATE TABLE system.session_history (
  LIKE system.session,
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deleted_at tracking_at
);
COMMENT ON TABLE system.session_history IS 'shortname: sys_sh';

GRANT SELECT,INSERT,DELETE,TRUNCATE ON system.session TO lysref_server;
GRANT SELECT,INSERT ON system.session_history TO lysref_server;
