
-- schemas and default privileges
-- new schemas also need to be added to the config toml file

----------------

CREATE SCHEMA aws AUTHORIZATION lysref_owner;
COMMENT ON SCHEMA aws IS 'shortname: aws';

GRANT USAGE ON SCHEMA aws TO lysref_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA aws GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO lysref_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA aws GRANT USAGE, SELECT ON SEQUENCES TO lysref_server;

GRANT USAGE ON SCHEMA aws TO lysref_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA aws GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO lysref_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA aws GRANT USAGE, SELECT ON SEQUENCES TO lysref_cli;

----------------

CREATE SCHEMA core AUTHORIZATION lysref_owner;
-- no shortname for core schema

GRANT USAGE ON SCHEMA core TO lysref_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO lysref_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT USAGE, SELECT ON SEQUENCES TO lysref_server;

GRANT USAGE ON SCHEMA core TO lysref_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO lysref_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT USAGE, SELECT ON SEQUENCES TO lysref_cli;

----------------

CREATE SCHEMA digmark AUTHORIZATION lysref_owner;
COMMENT ON SCHEMA digmark IS 'shortname: dm';

GRANT USAGE ON SCHEMA digmark TO lysref_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA digmark GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO lysref_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA digmark GRANT USAGE, SELECT ON SEQUENCES TO lysref_server;

GRANT USAGE ON SCHEMA digmark TO lysref_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA digmark GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO lysref_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA digmark GRANT USAGE, SELECT ON SEQUENCES TO lysref_cli;

-- MCP user currently only needs select
GRANT USAGE ON SCHEMA digmark TO lysref_mcp;
ALTER DEFAULT PRIVILEGES IN SCHEMA digmark GRANT SELECT ON TABLES TO lysref_mcp;
ALTER DEFAULT PRIVILEGES IN SCHEMA digmark GRANT USAGE, SELECT ON SEQUENCES TO lysref_mcp;

----------------

CREATE SCHEMA ecb AUTHORIZATION lysref_owner;
-- fixed schema: no shortname

GRANT USAGE ON SCHEMA ecb TO lysref_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA ecb GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO lysref_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA ecb GRANT USAGE, SELECT ON SEQUENCES TO lysref_server;

GRANT USAGE ON SCHEMA ecb TO lysref_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA ecb GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO lysref_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA ecb GRANT USAGE, SELECT ON SEQUENCES TO lysref_cli;

----------------

CREATE SCHEMA geo AUTHORIZATION lysref_owner;
COMMENT ON SCHEMA geo IS 'shortname: g';

GRANT USAGE ON SCHEMA geo TO lysref_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA geo GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO lysref_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA geo GRANT USAGE, SELECT ON SEQUENCES TO lysref_server;

GRANT USAGE ON SCHEMA geo TO lysref_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA geo GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO lysref_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA geo GRANT USAGE, SELECT ON SEQUENCES TO lysref_cli;

----------------

CREATE SCHEMA maxmind AUTHORIZATION lysref_owner;
COMMENT ON SCHEMA maxmind IS 'shortname: mm';

GRANT USAGE ON SCHEMA maxmind TO lysref_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA maxmind GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO lysref_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA maxmind GRANT USAGE, SELECT ON SEQUENCES TO lysref_server;

GRANT USAGE ON SCHEMA maxmind TO lysref_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA maxmind GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO lysref_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA maxmind GRANT USAGE, SELECT ON SEQUENCES TO lysref_cli;

----------------

CREATE SCHEMA process AUTHORIZATION lysref_owner;
COMMENT ON SCHEMA process IS 'shortname: proc';

GRANT USAGE ON SCHEMA process TO lysref_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA process GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO lysref_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA process GRANT USAGE, SELECT ON SEQUENCES TO lysref_server;

GRANT USAGE ON SCHEMA process TO lysref_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA process GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO lysref_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA process GRANT USAGE, SELECT ON SEQUENCES TO lysref_cli;

----------------

CREATE SCHEMA publisher AUTHORIZATION lysref_owner;
COMMENT ON SCHEMA publisher IS 'shortname: pub';

GRANT USAGE ON SCHEMA publisher TO lysref_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA publisher GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO lysref_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA publisher GRANT USAGE, SELECT ON SEQUENCES TO lysref_server;

GRANT USAGE ON SCHEMA publisher TO lysref_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA publisher GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO lysref_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA publisher GRANT USAGE, SELECT ON SEQUENCES TO lysref_cli;

----------------

CREATE SCHEMA supplier AUTHORIZATION lysref_owner;
COMMENT ON SCHEMA supplier IS 'shortname: s';

GRANT USAGE ON SCHEMA supplier TO lysref_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA supplier GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO lysref_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA supplier GRANT USAGE, SELECT ON SEQUENCES TO lysref_server;

GRANT USAGE ON SCHEMA supplier TO lysref_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA supplier GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO lysref_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA supplier GRANT USAGE, SELECT ON SEQUENCES TO lysref_cli;

-- allow schema access to external supplier users
GRANT USAGE ON SCHEMA supplier TO lysref_supplier;

----------------

CREATE SCHEMA system AUTHORIZATION lysref_owner;
COMMENT ON SCHEMA system IS 'shortname: sys';

GRANT USAGE ON SCHEMA system TO lysref_server;
GRANT USAGE ON SCHEMA system TO lysref_cli;
