
CREATE TABLE digmark.vertical
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  name text_short_mandatory UNIQUE, -- natural key
  updated_at tracking_at
);
COMMENT ON TABLE digmark.vertical IS 'shortname: dm_v';


CREATE TABLE digmark.campaign
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_fk bigint NOT NULL REFERENCES geo.country(id) CHECK (country_fk >= 1), -- disallow -1 (None)
  created_at tracking_at,
  daily_budget_eur numeric NOT NULL CHECK (daily_budget_eur BETWEEN 0 AND 10000),
  is_active boolean NOT NULL,
  manager digmark.manager NOT NULL,
  name text_short_mandatory NOT NULL UNIQUE,
  updated_at tracking_at,
  vertical_fk bigint NOT NULL REFERENCES digmark.vertical(id),
  UNIQUE (country_fk, vertical_fk) -- natural key
);
COMMENT ON TABLE digmark.campaign IS 'shortname: dm_c';


CREATE TABLE digmark.campaign_performance
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_fk bigint NOT NULL REFERENCES digmark.campaign(id),
  clicks int NOT NULL CHECK (clicks >= 0),
  conversions int NOT NULL CHECK (conversions >= 0),
  created_at tracking_at,
  day_cet date NOT NULL,
  impressions int NOT NULL CHECK (impressions >= 0),
  profit_eur numeric(12,2) NOT NULL GENERATED ALWAYS AS (revenue_eur - spend_eur) STORED,
  revenue_eur numeric(12,2) NOT NULL CHECK (revenue_eur >= 0),
  return_on_investment numeric NOT NULL GENERATED ALWAYS AS (CASE WHEN spend_eur = 0 THEN 0.0 ELSE revenue_eur/spend_eur - 1 END) STORED,
  spend_eur numeric(12,2) NOT NULL CHECK (spend_eur >= 0),
  updated_at tracking_at,
  UNIQUE (campaign_fk, day_cet) -- natural key
);
COMMENT ON TABLE digmark.campaign_performance IS 'shortname: dm_cp';


-- unlogged: data is generated by aggregation process
CREATE UNLOGGED TABLE digmark.campaign_performance_aggregated
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_fk bigint NOT NULL,
  clicks int NOT NULL,
  conversions int NOT NULL,
  created_at tracking_at,
  end_day date NOT NULL,
  impressions int NOT NULL,
  period core.performance_period NOT NULL,
  profit_eur numeric(12,2) NOT NULL GENERATED ALWAYS AS (revenue_eur - spend_eur) STORED,
  revenue_eur numeric(12,2) NOT NULL,
  return_on_investment numeric NOT NULL GENERATED ALWAYS AS (CASE WHEN spend_eur = 0 THEN 0.0 ELSE revenue_eur/spend_eur - 1 END) STORED,
  spend_eur numeric(12,2) NOT NULL,
  start_day date NOT NULL,
  trend numeric NOT NULL,
  volatility numeric NOT NULL,
  UNIQUE (period, campaign_fk) -- natural key
);
COMMENT ON TABLE digmark.campaign_performance_aggregated IS 'shortname: dm_cpa';


CREATE TABLE digmark.generated_campaign
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  body text NOT NULL,
  call_to_action text_short_mandatory,
  created_at tracking_at,
  headline text_short_mandatory,
  image_path text NOT NULL,
  model text_short_mandatory,
  product text_short_mandatory
);
COMMENT ON TABLE digmark.generated_campaign IS 'shortname: dm_gc';


-- abstract table for partner-specific launchers (Facebook, Google Ads, etc.)
CREATE TABLE digmark.launcher
(
  id bigint,
  country_fk bigint NOT NULL DEFAULT -1, -- set during preparation
  created_at tracking_at,
  created_at_day date NOT NULL GENERATED ALWAYS AS (date(created_at AT TIME ZONE 'Europe/Berlin')) STORED, -- for easy filtering by date
  daily_budget_eur numeric NOT NULL CHECK (daily_budget_eur BETWEEN 1 AND 10000),
  manager digmark.manager NOT NULL,
  max_steps int NOT NULL, -- default set by sub-table
  message text NOT NULL DEFAULT '', -- set during preparation and processing
  name text_short_mandatory NOT NULL,
  partner digmark.partner NOT NULL, -- default set by sub-table
  status digmark.launcher_status NOT NULL DEFAULT 'Unprepared',
  step int NOT NULL DEFAULT 0, -- set during processing
  updated_at tracking_at,
  vertical_fk bigint NOT NULL DEFAULT -1, -- set during preparation
  CHECK (false) NO INHERIT -- prevents direct inserts, but not to children. Additional check only: main abstraction enforcement is REVOKE below
);
COMMENT ON TABLE digmark.launcher IS 'shortname: dm_l';

-- make digmark.launcher abstract
REVOKE INSERT,UPDATE,DELETE ON digmark.launcher FROM lysref_server;
REVOKE INSERT,UPDATE,DELETE ON digmark.launcher FROM lysref_cli;


CREATE TABLE digmark.launcher_fb
(
  fan_page text NOT NULL,
  fb_account_id text NOT NULL DEFAULT '', -- set during preparation
  fb_campaign_id text NOT NULL DEFAULT '', -- set during processing (step 2)
  fb_creative_id text NOT NULL DEFAULT '' -- set during processing (step 1)
)
INHERITS (digmark.launcher);
ALTER TABLE digmark.launcher_fb ADD PRIMARY KEY (id);
ALTER TABLE digmark.launcher_fb ALTER COLUMN id SET DEFAULT nextval('digmark.launcher_seq'::regclass); -- shared sequence
ALTER TABLE digmark.launcher_fb ADD CONSTRAINT launcher_fb_country_fk_fkey FOREIGN KEY(country_fk) REFERENCES geo.country(id);
ALTER TABLE digmark.launcher_fb ADD CONSTRAINT launcher_fb_name_uq UNIQUE (name);
ALTER TABLE digmark.launcher_fb ALTER COLUMN max_steps SET DEFAULT 2;
ALTER TABLE digmark.launcher_fb ALTER COLUMN partner SET DEFAULT 'Facebook';
ALTER TABLE digmark.launcher_fb ADD CONSTRAINT launcher_fb_vertical_fk_fkey FOREIGN KEY(vertical_fk) REFERENCES digmark.vertical(id);

COMMENT ON TABLE digmark.launcher_fb IS 'shortname: dm_l_fb';
CREATE INDEX launcher_fb_day_idx ON digmark.launcher_fb USING btree(created_at_day);
CREATE INDEX launcher_fb_status_unprepared_idx ON digmark.launcher_fb USING btree(status) WHERE status = 'Unprepared';


CREATE TABLE digmark.launcher_gads
(
  gads_account_id bigint NOT NULL DEFAULT 0, -- set during preparation
  gads_ad_id bigint NOT NULL DEFAULT 0, -- set during processing (step 3)
  gads_ad_group_id bigint NOT NULL DEFAULT 0, -- set during processing (step 2)
  gads_campaign_id bigint NOT NULL DEFAULT 0 -- set during processing (step 1)
)
INHERITS (digmark.launcher);
ALTER TABLE digmark.launcher_gads ADD PRIMARY KEY (id);
ALTER TABLE digmark.launcher_gads ALTER COLUMN id SET DEFAULT nextval('digmark.launcher_seq'::regclass); -- shared sequence
ALTER TABLE digmark.launcher_gads ADD CONSTRAINT launcher_gads_country_fk_fkey FOREIGN KEY(country_fk) REFERENCES geo.country(id);
ALTER TABLE digmark.launcher_gads ADD CONSTRAINT launcher_gads_name_uq UNIQUE (name);
ALTER TABLE digmark.launcher_gads ALTER COLUMN max_steps SET DEFAULT 3;
ALTER TABLE digmark.launcher_gads ALTER COLUMN partner SET DEFAULT 'Google Ads';
ALTER TABLE digmark.launcher_gads ADD CONSTRAINT launcher_gads_vertical_fk_fkey FOREIGN KEY(vertical_fk) REFERENCES digmark.vertical(id);

COMMENT ON TABLE digmark.launcher_gads IS 'shortname: dm_l_gads';
CREATE INDEX launcher_gads_day_idx ON digmark.launcher_gads USING btree(created_at_day);
CREATE INDEX launcher_gads_status_unprepared_idx ON digmark.launcher_gads USING btree(status) WHERE status = 'Unprepared';