
CREATE TABLE digmark.vertical
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  name text_short_mandatory UNIQUE, -- natural key
  updated_at tracking_at
);
COMMENT ON TABLE digmark.vertical IS 'shortname: dm_v';


CREATE TABLE digmark.campaign
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_fk bigint NOT NULL REFERENCES geo.country(id) CHECK (country_fk >= 1), -- disallow -1 (None)
  created_at tracking_at,
  daily_budget_eur numeric NOT NULL CHECK (daily_budget_eur BETWEEN 0 AND 10000),
  is_active boolean NOT NULL,
  manager digmark.manager NOT NULL,
  name text_short_mandatory NOT NULL UNIQUE,
  updated_at tracking_at,
  vertical_fk bigint NOT NULL REFERENCES digmark.vertical(id),
  UNIQUE (country_fk, vertical_fk) -- natural key
);
COMMENT ON TABLE digmark.campaign IS 'shortname: dm_c';


CREATE TABLE digmark.campaign_performance
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_fk bigint NOT NULL REFERENCES digmark.campaign(id),
  clicks int NOT NULL CHECK (clicks >= 0),
  conversions int NOT NULL CHECK (conversions >= 0),
  created_at tracking_at,
  day_cet date NOT NULL,
  impressions int NOT NULL CHECK (impressions >= 0),
  profit_eur numeric(12,2) NOT NULL GENERATED ALWAYS AS (revenue_eur - spend_eur) STORED,
  revenue_eur numeric(12,2) NOT NULL CHECK (revenue_eur >= 0),
  return_on_investment numeric NOT NULL GENERATED ALWAYS AS (CASE WHEN spend_eur = 0 THEN 0.0 ELSE revenue_eur/spend_eur - 1 END) STORED,
  spend_eur numeric(12,2) NOT NULL CHECK (spend_eur >= 0),
  updated_at tracking_at,
  UNIQUE (campaign_fk, day_cet) -- natural key
);
COMMENT ON TABLE digmark.campaign_performance IS 'shortname: dm_cp';


-- unlogged: data is generated by aggregation process
CREATE UNLOGGED TABLE digmark.campaign_performance_aggregated
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_fk bigint NOT NULL,
  clicks int NOT NULL,
  conversions int NOT NULL,
  created_at tracking_at,
  end_day date NOT NULL,
  impressions int NOT NULL,
  period core.performance_period NOT NULL,
  profit_eur numeric(12,2) NOT NULL GENERATED ALWAYS AS (revenue_eur - spend_eur) STORED,
  revenue_eur numeric(12,2) NOT NULL,
  return_on_investment numeric NOT NULL GENERATED ALWAYS AS (CASE WHEN spend_eur = 0 THEN 0.0 ELSE revenue_eur/spend_eur - 1 END) STORED,
  spend_eur numeric(12,2) NOT NULL,
  start_day date NOT NULL,
  trend numeric NOT NULL,
  volatility numeric NOT NULL,
  UNIQUE (period, campaign_fk) -- natural key
);
COMMENT ON TABLE digmark.campaign_performance_aggregated IS 'shortname: dm_cpa';