
CREATE TABLE core.array_type
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  c_bool boolean[] NOT NULL,
  c_date date[] NOT NULL,
  c_enum core.mandatory_enum[] NOT NULL,
  c_int int[] NOT NULL,
  c_numeric numeric[] NOT NULL,
  c_text text[] NOT NULL,
  created_at tracking_at,
  updated_at tracking_at
);
COMMENT ON TABLE core.array_type IS 'shortname: at';


-- differentiate between mandatory defaults (enforced by app or db) and a suggested default value
CREATE TABLE core.default_value
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  c_default_text varchar(64) NOT NULL DEFAULT 'Default text' CHECK (c_default_text != ''), -- set default here for use when importing directly into db
  c_suggested_text text_short_mandatory,
  created_at tracking_at,
  updated_at tracking_at
);
COMMENT ON TABLE core.default_value IS 'shortname: dv';


CREATE TABLE core.mandatory_value
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- zero value false is valid
  -- if possible, name the column such that false is the default, so that true stands out in UI
  c_bool boolean NOT NULL,

  -- zero value 0001-01-01 is invalid: enforce minimum date via domain
  -- suffix the column with the timezone, e.g. _cet for GMT+1
  c_date_cet date_mandatory,

  -- no zero value: this enum has no empty string value
  c_enum core.mandatory_enum NOT NULL,

  -- zero value 0 is valid
  c_int int NOT NULL,

  -- zero value 0.0 is valid
  c_numeric numeric NOT NULL,

  -- no zero value: joined table does not have a 0 ID or -1 (None) value
  -- suffix foreign keys with "_fk"
  c_table_fk bigint NOT NULL REFERENCES geo.ocean(id),

  -- zero value '' is invalid: enforce non-zero value via domain
  c_text text_short_mandatory,

  -- zero value 00:00:00 is valid
  c_time time NOT NULL,

  created_at tracking_at,
  updated_at tracking_at
);
COMMENT ON TABLE core.mandatory_value IS 'shortname: mv';


-- all zero values are allowed and shown in comment
CREATE TABLE core.optional_value
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  c_bool boolean NOT NULL, -- false
  c_date_cet date NOT NULL, -- 0001-01-01
  c_enum core.optional_enum NOT NULL, -- '' (enum contains empty value '')
  c_int int NOT NULL, -- 0
  c_numeric numeric NOT NULL, -- 0.0
  c_table_fk bigint NOT NULL REFERENCES geo.country(id), -- -1 (joined table contains -1 (None) value)
  c_text text_short, -- ''. Note that domain allows '' but limits max text length
  c_time time NOT NULL, -- 00:00:00
  created_at tracking_at,
  updated_at tracking_at
);
COMMENT ON TABLE core.optional_value IS 'shortname: ov';


CREATE TABLE core.variant_type
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  c_constrained_text varchar(6) NOT NULL CHECK (LENGTH(c_constrained_text) = 6 AND c_constrained_text ~ '^[A-Z]+$'),
  c_ip inet NOT NULL,
  c_long_text varchar(1000) NOT NULL,
  c_money_amount numeric(12,2) NOT NULL, -- NB: for fractional money, use plain numeric
  c_percent numeric NOT NULL,
  created_at tracking_at,
  updated_at tracking_at
);
COMMENT ON TABLE core.variant_type IS 'shortname: vt';