
CREATE TYPE tedb.vat_rate_type AS ENUM ('DEFAULT', 'EXEMPTED', 'NOT_APPLICABLE', 'OUT_OF_SCOPE', 'PARKING_RATE', 'REDUCED_RATE', 'SUPER_REDUCED_RATE');

CREATE TYPE tedb.vat_type AS ENUM ('REDUCED', 'STANDARD');
