<template>
  <v-container fluid>
    <v-responsive>
      <v-row density="compact" class="mt-2">
        <v-col cols="auto">
          <v-card variant="flat">
            <v-card-text class="pb-0">
              <span class="dt-title">{{ $t('generation.title') }}</span>
            </v-card-text>
          </v-card>
        </v-col>
      </v-row>

      <v-row density="compact">
        <v-col cols="auto">
          <v-card variant="flat">
            <v-card-text>

              <div class="dt-subtitle">Demonstrates use of generative AI. Campaign text is generated by requesting structured data from the Gemini API.</div>

            </v-card-text>
          </v-card>
        </v-col>
      </v-row>

      <v-row class="ml-4">
        <v-col cols="auto">
          <div class="text-headline-small">Saved campaigns</div>
        </v-col>
      </v-row>

      <v-row class="ml-4 pb-6">
        <v-col v-for="camp in items" :key="camp.id" cols="auto">
          <v-card elevation="3" width="650">
            <v-card-title>{{ camp.headline }}</v-card-title>

            <v-card-text>
              <v-row class="align-center">
                <v-rating :model-value="4.5" color="#D0D0D0" :active-color="'rgb(var(--v-theme-primary))'" 
                  density="compact" size="small" half-increments readonly></v-rating>
                <div class="text-grey ms-4">4.5 (413)</div>
              </v-row>

              <div class="mt-4">{{ camp.body }}</div>
            </v-card-text>

            <v-card-actions>
              <v-btn :color="'rgb(var(--v-theme-secondary))'" border>{{ camp.call_to_action }}</v-btn>
            </v-card-actions>

            <v-divider class="mt-4"></v-divider>

            <v-list-item prepend-icon="mdi-account-arrow-right" :subtitle="camp.product + ' (' + camp.model + ')'"></v-list-item>
          </v-card>
        </v-col>
      </v-row>

    </v-responsive>
  </v-container>
</template>

<script lang="ts" setup>
import { onMounted } from 'vue'
import { useTableState } from 'lys-vue'
import ax from '@/api'
import { type GeneratedCampaign } from '@/types/digmark'

const genUrl = '/a/gemini/generate-marketing-campaign'

const savedCampsUrl = '/a/digmark/generated-campaigns'

const { items, loadItems } = useTableState<GeneratedCampaign>({ ax, baseUrl: savedCampsUrl})

onMounted(() => {
  loadItems({ page: 1, itemsPerPage: 8, sortBy: [] })
})

</script>
