<template>
  <v-container fluid>
    <v-responsive>
      <v-row density="compact" class="mt-2">
        <v-col cols="auto">
          <v-card variant="flat">
            <v-card-text class="pb-0">
              <span class="dt-title">{{ $t('generation.title') }}</span>
            </v-card-text>
          </v-card>
        </v-col>
      </v-row>

      <v-row density="compact">
        <v-col cols="auto">
          <v-card variant="flat">
            <v-card-text>

              <div class="dt-subtitle">In backend, demonstrates use of generative AI via API. Campaign text is generated by requesting structured data from the Gemini API.</div>

            </v-card-text>
          </v-card>
        </v-col>
      </v-row>

      <v-form ref="genForm" class="ml-4 mt-2">
        <div class="d-flex ga-4 align-center">
          <v-text-field label="Product or service" v-model="product" placeholder="Trip to London, Car insurance" max-width="400"
            :rules="[(v: string) => !!v || 'Product or service is required']"
          ></v-text-field>
          <v-select label="Text model" v-model="textModel" max-width="250"
            :rules="[(v: string) => !!v || 'Text model is required']"
          ></v-select>
          <v-btn class="mb-2" color="primary" :loading="generating">Generate</v-btn>
        </div>
      </v-form>

      <v-card v-if="showEditForm" variant="flat" max-width="650">
        <v-card-title>Generated campaign</v-card-title>
        <v-card-text>
          <v-form ref="editForm" class="ml-4 mt-2">
            <v-text-field label="Headline" v-model="headline"
              :rules="[(v: string) => !!v || 'Headline is required']"
            ></v-text-field>
            <v-textarea label="Body" v-model="body"
              :rules="[(v: string) => !!v || 'Body is required']"
            </v-textarea>
            <v-text-field label="Call to action" v-model="callToAction"
              :rules="[(v: string) => !!v || 'Call to action is required']"
            ></v-text-field>
          </v-form>
          <div class="ml-4 d-flex ga-4 align-center">
            <v-btn class="mb-2" color="primary">Save</v-btn>
            <v-btn class="mb-2" @click="reject">Reject</v-btn>
          </div>
        </v-card-text>
      </v-card>

      <v-row class="ml-4 mt-4">
        <v-col cols="auto">
          <div class="text-headline-small">Saved campaigns</div>
        </v-col>
      </v-row>

      <v-row class="ml-4 pb-6">
        <v-col v-for="camp in items" :key="camp.id" cols="auto">
          <v-card elevation="2" max-width="650">
            <v-card-title>{{ camp.headline }}</v-card-title>

            <v-card-text>
              <v-row class="align-center">
                <v-rating :model-value="4.5" color="#D0D0D0" :active-color="'rgb(var(--v-theme-primary))'" 
                  density="compact" size="small" half-increments readonly></v-rating>
                <div class="text-grey ms-4">4.5 (413)</div>
              </v-row>

              <div class="mt-4">{{ camp.body }}</div>
            </v-card-text>

            <v-card-actions>
              <v-btn :color="'rgb(var(--v-theme-secondary))'" border prepend-icon="mdi-star-four-points">{{ camp.call_to_action }}</v-btn>
            </v-card-actions>

            <v-divider class="mt-4"></v-divider>

            <v-list-item prepend-icon="mdi-account-arrow-right" :subtitle="camp.product + ' (' + camp.model + ')'"></v-list-item>
          </v-card>
        </v-col>
      </v-row>

    </v-responsive>
  </v-container>
</template>

<script lang="ts" setup>
import { ref, computed, onMounted } from 'vue'
import { useTableState } from 'lys-vue'
import ax from '@/api'
import { type GeneratedCampaign } from '@/types/digmark'

const product = ref<string>('')
const textModel = ref<string>('gemini-3.1-flash-lite')
const genUrl = '/a/gemini/generate-marketing-campaign'
const generating = ref<boolean>(false)

const headline = ref<string>('')
const body = ref<string>('')
const callToAction = ref<string>('')
const showEditForm = computed(() => !!headline.value || !!body.value || !!callToAction.value)

const savedCampsUrl = '/a/digmark/generated-campaigns'

const { items, loadItems } = useTableState<GeneratedCampaign>({ ax, baseUrl: savedCampsUrl})

function generate() {
  generating.value = true
  ax.post(genUrl, {'product': product.value, 'model': textModel.value})
    .then(resp => {
      headline.value = resp.data.data.headline ?? ''
      body.value = resp.data.data.body ?? ''
      callToAction.value = resp.data.data.call_to_action ?? ''
    })
    .catch() // handled by interceptor
    .finally(() => generating.value = false)
}

function reject() {
  headline.value = ''
  body.value = ''
  callToAction.value = ''
}

onMounted(() => {
  loadItems({ page: 1, itemsPerPage: 8, sortBy: [] })
})

</script>
