
CREATE TABLE geo.ocean
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  description text_short_mandatory UNIQUE,
  name text_short_mandatory UNIQUE,
  updated_at tracking_at
);
COMMENT ON TABLE geo.ocean IS 'shortname: geo_o';


CREATE TABLE geo.country
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  is_active boolean NOT NULL DEFAULT false,
  iso2 char(2) NOT NULL UNIQUE CHECK (iso2 ~ '^[A-Z]+$'), -- ~ for case sensitive match, ^ and $ to to match whole string
  name text_short_mandatory UNIQUE,
  updated_at tracking_at
);
COMMENT ON TABLE geo.country IS 'shortname: geo_c';

